# Site settings
title: "Marie-Line Delacroix"
description: "Modiste - Création de chapeaux couture"

emails:
  - atelier7@ml-delacroix.fr
  - ml-delacroix@pygmeeweb.com

baseurl: ""
url: "http://ml-delacroix.fr"

language: fr

logoImage: logo-atelier-7-marie-line-delacroix-rose-optim.svg

google_analytics_tracking_id: "UA-83807575-1"

timezone: "Europe/Paris"

collections:

  catalog:
    output: true
  values:
    layout: item

defaults:
  -
    scope:
      type: pages
      path: "pages"
    values:
      permalink: /:basename/
      layout: default

  -
    scope:
      type: pages
      path: "pages/catalog-indexes"
    values:
      layout: catalog-category

  -
    scope:
      type: catalog
    values:
      layout: "catalog-item"
      permalink: /:path/

  - { scope: { path: "_catalog/accessoires" }, values: { type: "accessoires" } }
  - { scope: { path: "_catalog/ete" }, values: { type: "ete" } }
  - { scope: { path: "_catalog/hiver" }, values: { type: "hiver" } }
  - { scope: { path: "_catalog/le-saharien" }, values: { type: "le-saharien" } }
  - { scope: { path: "_catalog/mi-saison" }, values: { type: "mi-saison" } }
  - { scope: { path: "_catalog/soiree-ceremonie" }, values: { type: "soiree-ceremonie" } }
  - { scope: { path: "_catalog/homme" }, values: { type: "homme" } }

sass:

  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  style: nested

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
  # parse markdown inside block-level HTML tag
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml
  - scripts/*
  - bower.json
  - Readme.md
  - publish-key.enc
  # - _catalog/hiver
  # - _catalog/mi-saison

gems: [jekyll/responsive_image]

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 50

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 550  # [Required] How wide the resized image will be.
      quality: 50 # [Optional] Overrides default_quality for this size.
    - width: 470
    - width: 350
    - width: 300
    - width: 250
    - width: 150
    - width: 50
      quality: 30

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: img

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: img/resized/%{width}/%{basename}

  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  # extra_images:
  #   - assets/foo/bar.png
  #   - assets/bgs/*.png
  #   - assets/avatars/*.{jpeg,jpg}

# ++++++++++++++++++++++++++++++++++++ Marie-Line Delacroix +++++++++++++++++++++++++++++++++++++++
#                                      Specific setup

# saisons used in items front matter
saisons : { "e": "Eté", "h": "Hiver", "m": "Mi-saison" }

# Categories du catalogue
# utilisé pour générer les menus
catalog-categories:
  -
    # minuscules, chiffres et tiret
    name: ete

    # utilisé pour l'affichage dans les pages
    # sans cette valeur, "name" est utilisé avec "Capitalisation" accessoires > Accessoires
    # collection-ete > Collection-Ete n'étant pas très beau, on utilise une valeur "display"
    display: Eté
  -
    name: hiver
    display: Hiver
  -
    name: mi-saison
    display: Mi-saison
  -
    name: le-saharien
    display: Le Saharien
  -
    name: soiree-ceremonie
    display: Soirée, Cérémonie, Cocktail

  -
    name: homme
  -
    name: accessoires

figure:

  normal:
    classes: "col-md-3 col-sm-3 col-xs-6"
    sizes: "(min-width:1200px) 300px, (min-width:992px) 230px, (min-width:768px) 180px, 50vw"

  big:
    classes: "col-md-6 col-sm-6 col-xs-12"
    sizes: "(min-width:1200px) 520px, (min-width:992px) 470px, (min-width:768px) 350px, 90vw"

  carousel:
    classes: ""
    sizes: "(min-width:1200px) 50vw, (min-width:992px) 470px, (min-width:768px) 350px, 90vw"

  carousel-thumbs:
    classes: ""
    sizes: "(min-width:1200px) 50px, 50px"

# used to create a menu hierarchy for a type (pages, collection, ...)
# depending on a starting folder (eg : _mycollection/folder1)
# see _includes/header.html
main-menu-dropdowns:

  -
    label: catalog
    weight: 32

rotation-classes:
  - rot0
  - rot4
  - rot2
  - rot1
  - rot3
  - rot2
  - rot4
  - rot0
  - rot2
  - tor3

# ++++++++++++++++++++++ admin view page setup +++++++++++++++++++++++


admin:

  doDebug : true

  content-types:

    pages:
      displayProps:
        - url
        - title
        - menu
        - weight
        - permalink
        - layout
        - dir
        - name
        - path
      noDisplayProps:
        - content

    catalog:
      displayProps:
       - path
       - url
       - type
       - title
       - date
       - slug
       - ext
       - tags

      noDisplayProps:
       - id
       - matieres
       - taille
       - prix
       - images
       - output
       - content
       - collection
       - excerpt
       - previous
       - next
       - draft
       - categories
       - layout
       - relative_path
       - permalink

    posts:
      displayProps:
       - path
       - url
       - type
       - title
       - date
       - slug
       - ext
       - tags

      noDisplayProps:
       - id
       - matieres
       - taille
       - prix
       - images
       - output
       - content
       - collection
       - excerpt
       - previous
       - next
       - draft
       - categories
       - layout
       - relative_path
       - permalink
