# Site settings
title: "Marie-Line Delacroix"
description: "Modiste - Créatrice de chapeaux couture"

# email: ml-delacroix@gmail.com
email: david.jacquel@gmail.com

baseurl: ""
url: "http://ml-delacroix.fr"

collections:

  catalog:
    output: true
  values:
    layout: item

defaults:
  -
    scope:
      type: pages
      path: "pages"
    values:
      permalink: /:basename/
      layout: default

  -
    scope:
      type: pages
      path: "pages/catalog-indexes"
    values:
      layout: catalog-category

  -
    scope:
      type: catalog
    values:
      layout: "catalog-item"
      permalink: /:path/
  -
    scope:
      path: "_catalog/chapeaux"
    values:
      type: "chapeau"
  -
    scope:
      path: "_catalog/accessoires"
    values:
      type: "accessoire"

sass:

  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  style: nested

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml
  - scripts/*
  - bower.json
  - Readme.md
  - publish-key.enc

# Marie-Line Delacroix
# Specific setup

# saisons used in items front matter
saisons : { "p": "Printemps", "e": "Eté", "a": "Automne", "h": "Hiver" }

# Categories du catalogue
# utilisé pour générer les menus
catalog-categories:
  -
    name: casquettes
    color: "#f00"
  -
    name: accessoires
    color: "#00f"

# used to create a menu hierarchy for a type (pages, collection, ...)
# depending on a starting folder (eg : _mycollection/folder1)
# see _includes/header.html
main-menu-dropdowns:

  -
    label: catalog
    weight: 32

rotation-classes:
  - rot0
  - rot4
  - rot2
  - rot1
  - rot3
  - rot2
  - rot4
  - rot0
  - rot2
  - tor3
