# Site settings
title: "Marie-Line Delacroix"
description: "Modiste - Créatrice de chapeaux couture"

emails:
  - atelier7@ml-delacroix.fr
  - ml-delacroix@pygmeeweb.com

baseurl: ""
url: "http://ml-delacroix.fr"

google_analytics_tracking_id: "UA-83807575-1"

timezone: "Europe/Paris"

collections:

  catalog:
    output: true
  values:
    layout: item

defaults:
  -
    scope:
      type: pages
      path: "pages"
    values:
      permalink: /:basename/
      layout: default

  -
    scope:
      type: pages
      path: "pages/catalog-indexes"
    values:
      layout: catalog-category

  -
    scope:
      type: catalog
    values:
      layout: "catalog-item"
      permalink: /:path/

  - { scope: { path: "_catalog/accessoires" }, values: { type: "accessoire" } }
  - { scope: { path: "_catalog/ete" }, values: { type: "ete" } }
  - { scope: { path: "_catalog/hiver" }, values: { type: "hiver" } }
  - { scope: { path: "_catalog/le-saharien" }, values: { type: "le-saharien" } }
  - { scope: { path: "_catalog/mi-saison" }, values: { type: "mi-saison" } }
  - { scope: { path: "_catalog/soiree-ceremonie" }, values: { type: "soiree-ceremonie" } }
  - { scope: { path: "_catalog/homme" }, values: { type: "homme" } }

sass:

  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  style: nested

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
  # parse markdown inside block-level HTML tag
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml
  - scripts/*
  - bower.json
  - Readme.md
  - publish-key.enc

# ++++++++++++++++++++++++++++++++++++ Marie-Line Delacroix +++++++++++++++++++++++++++++++++++++++
#                                      Specific setup

# saisons used in items front matter
saisons : { "e": "Eté", "h": "Hiver", "m": "Mi-saison" }

# Categories du catalogue
# utilisé pour générer les menus
catalog-categories:
  -
    # minuscules, chiffres et tiret
    name: ete

    # utilisé pour l'affichage dans les pages
    # sans cette valeur, "name" est utilisé avec "Capitalisation" accessoires > Accessoires
    # collection-ete > Collection-Ete n'étant pas très beau, on utilise une valeur "display"
    display: Eté
  -
    name: hiver
    display: Hiver
  -
    name: mi-saison
    display: Mi-saison
  -
    name: le-saharien
    display: Le Saharien
  -
    name: soiree-ceremonie
    display: Soirée, Cérémonie, Cocktail

  -
    name: homme
  -
    name: accessoires




# used to create a menu hierarchy for a type (pages, collection, ...)
# depending on a starting folder (eg : _mycollection/folder1)
# see _includes/header.html
main-menu-dropdowns:

  -
    label: catalog
    weight: 32

rotation-classes:
  - rot0
  - rot4
  - rot2
  - rot1
  - rot3
  - rot2
  - rot4
  - rot0
  - rot2
  - tor3

# ++++++++++++++++++++++ admin view page setup +++++++++++++++++++++++


admin:

  doDebug : true

  content-types:

    pages:
      displayProps:
        - url
        - title
        - menu
        - weight
        - permalink
        - layout
        - dir
        - name
        - path
      noDisplayProps:
        - content

    catalog:
      displayProps:
       - path
       - url
       - type
       - title
       - date
       - slug
       - ext
       - tags

      noDisplayProps:
       - id
       - matieres
       - taille
       - prix
       - images
       - output
       - content
       - collection
       - excerpt
       - previous
       - next
       - draft
       - categories
       - layout
       - relative_path
       - permalink
